In [1]:
import pandas as pd
import json
from sklearn.model_selection import train_test_split

In [ ]:
dataset_sentiment = pd.read_json('full_data\\sentiment_score.json', lines=True)
dataset_sentiment = dataset_sentiment.rename(columns={'sentiment_score': 'roberta_score'})
dataset_sentiment

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code,sentiment,roberta_score,stars_3_scale
0,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24,Wawa,8,"Food, Coffee & Tea, Gas Stations, Restaurants,...",2544 W Main Street,Norristown,PA,19403,Positive,3,3
1,3MpDvy5gEdsbZh9-p92dHg,8QnuWGVNBhzyYXGSeRdi4g,4,0,0,0,After my ROTD yesterday of a different Sweet ...,2013-10-24 19:24:33,Sweet Cece's,17,"Food, Ice Cream & Frozen Yogurt",7114 Hwy 70 S,Nashville,TN,37221,Positive,3,3
2,bCla27ma_6i_QFrGkILKrQ,sLgnx_WFCjEoPsS6NwU70Q,5,0,0,0,Our family returned for breakfast again this w...,2014-10-27 16:31:37,Le Peep,259,"Event Planning & Services, Salad, Caterers, Am...",3036 N Eagle Rd,Meridian,ID,83646,Positive,3,3
3,UsBxLh14sUpO8SdeqIiGOA,Wy8Hswf2cLQGRZN6armkag,1,1,0,0,"If I could give it a zero, I would. I order a ...",2011-08-24 23:07:08,Jack in the Box,86,"Restaurants, Fast Food, Mexican, Tacos, Burger...",6875 Hollister Ave,Goleta,CA,93117,Negative,1,1
4,mEOMAeEonZoUx2nPM3v6fg,f-WhNOSwN1aB4nRFekf01g,4,0,0,0,Id you haven't been to the Smoothie King cente...,2015-03-19 00:30:09,Smoothie King,50,"Arts & Entertainment, Ticket Sales, Food, Juic...",1501 Dave Dixon Drive Space 101-102,New Orleans,LA,70113,Positive,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586656,6YRmtPVvnD_mexQifxAJsg,IkjBNJvMZhea1c3j2H2Ahw,3,0,0,0,"Besides it being super busy often, usually, I ...",2022-01-10 12:51:07,Starbucks,31,"Food, Coffee & Tea",2350 South Grand Ave,St. Louis,MO,63104,Positive,3,2
586657,6Hmh8UC5K0oBgp3_D5doDQ,BxveKq0rKp52EWooIDK54w,2,3,1,0,Where do i begin. Overall the food was fine. I...,2019-12-08 19:24:12,Denny's,88,"Breakfast & Brunch, American (Traditional), Re...",3155 E Fairview Ave,Meridian,ID,83642,Negative,1,1
586658,UfevNSM_H14XXWZFlHYPoA,TNtcjnta11CpDebuBNdoug,2,0,1,0,Our waiter was good but a bit rushed. I didn't...,2017-10-22 20:55:12,Red Robin Gourmet Burgers and Brews,83,"Home Services, American (New), Contractors, Am...",130 Gravois Bluffs Cir,Fenton,MO,63026,Negative,1,1
586659,LHWtjTG7e1NzNPYUbUo-9w,rgeuy1qbw6Z8B6CSVANHIA,5,1,1,1,I've been to the other Federal Donuts location...,2012-10-13 14:39:37,Federal Donuts,1464,"Donuts, Sandwiches, Soul Food, Food, Coffee & ...",1632 Sansom St,Philadelphia,PA,19103,Positive,3,3
586660,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5,1,0,1,Don't misinterpret my 5-star review....I don't...,2016-04-30 01:02:34,Wendy's,55,"Restaurants, Burgers, Food, Fast Food",2130 Hampton Avenue,St.Louis,MO,63139,Positive,3,3

In [9]:
#take data from Starbucks, McDonald's and Dunkin' to be our BI data for the final comparison
BI_df = dataset_sentiment[dataset_sentiment["name"].str.contains("Starbucks", na=False)]
#BI_df.drop(columns=['sentiment', 'roberta_score'], inplace=True)
BI_df

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code,sentiment,roberta_score,stars_3_scale
31,veBX5roHQLNnQ1rTtNh_gg,aJvxWyQIG5OLfBw3qAe8xA,2,0,0,0,"Ordered Caramel frappe at Drive thru, BIG MIST...",2017-12-29 19:38:31,Starbucks,65,"Restaurants, Coffee & Tea, Food",2308 Murfreesboro Pike,Nashville,TN,37217,Neutral,2,1
46,zZygOZLNyJX5nDqKrwa4HQ,MjZQqZAmJeMco_Vq-Y9h-g,4,0,0,0,Drum-roll please! Review #100 coming right up!...,2014-02-05 19:38:24,Starbucks,33,"Food, Coffee & Tea",13170 North Hazel Dell Pkwy,Carmel,IN,46033,Positive,3,3
54,0SpK7eVn5TrpyQKPaohVBw,u7MJKcNdZXYyTeb67vD5jw,4,1,0,0,We stopped here for my Chai and Hubby's coffee...,2017-02-09 04:35:39,Starbucks,17,"Food, Coffee & Tea",5 Hartford Rd,Mount Laurel,NJ,08054,Positive,3,3
89,IVnrNZ8npRx04jkNp6-ERA,saJFbz12EnzanelpD8_xXQ,2,0,0,0,There's been three times that I've ordered a g...,2016-08-25 14:08:18,Starbucks,95,"Food, Coffee & Tea",10716 Big Bend Rd,Riverview,FL,33579,Neutral,2,1
104,tgP2gKsf3O9MyuLuolv2oQ,KiE0h68HGOO7ZXAqkMBdiw,1,0,1,0,"I went in when they had 4 people working, wait...",2016-01-30 01:10:42,Starbucks,35,"Food, Coffee & Tea",1015 De La Vina St,Santa Barbara,CA,93101,Negative,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586567,QPDFn3SQqZeBu7OBI78g9w,-85kJMtb9wqNWDT8yLbitw,3,0,0,0,Fair service- messed up my drink cuppa times....,2021-12-13 22:08:14,Starbucks,34,"Food, Coffee & Tea","438 Main St, Space 168, Space 168",Franklin,TN,37064,Negative,1,2
586568,F3ELBqGgDCX9YEhz_oS0xQ,Ddg-J_j0YFErk7wpMtH_0A,5,3,1,4,On my way out of Reno last week I noted a new ...,2021-12-28 19:26:37,Starbucks,67,"Food, Coffee & Tea, Coffee Roasteries",986 Ambassador Dr,Reno,NV,89523,Positive,3,3
586638,TZJzzQsE4R7RmqkVRaLEKw,2rmpfdyV2POqpXtmPHO_IQ,1,0,0,0,always closing drive thru. i've driven here so...,2021-12-28 18:12:04,Starbucks,27,"Coffee & Tea, Food",6363 N La Cholla,Tucson,AZ,85741,Negative,1,1
586646,dvu83QWKsnnbGvNVQ3mv7A,GxuxCctcz3Hyk0wnuly7vQ,4,1,0,1,This is now one of two Starbucks in the shoppi...,2017-01-21 00:19:27,Starbucks,45,"Food, Coffee & Tea",4811 E Grant,Tucson,AZ,85712,Positive,3,3
586656,6YRmtPVvnD_mexQifxAJsg,IkjBNJvMZhea1c3j2H2Ahw,3,0,0,0,"Besides it being super busy often, usually, I ...",2022-01-10 12:51:07,Starbucks,31,"Food, Coffee & Tea",2350 South Grand Ave,St. Louis,MO,63104,Positive,3,2

In [10]:
#take rest data of the data to be our training data for the models
train_model_df = dataset_sentiment[~dataset_sentiment["name"].str.contains("Starbucks", na=False)]
train_model_df

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code,sentiment,roberta_score,stars_3_scale
0,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24,Wawa,8,"Food, Coffee & Tea, Gas Stations, Restaurants,...",2544 W Main Street,Norristown,PA,19403,Positive,3,3
1,3MpDvy5gEdsbZh9-p92dHg,8QnuWGVNBhzyYXGSeRdi4g,4,0,0,0,After my ROTD yesterday of a different Sweet ...,2013-10-24 19:24:33,Sweet Cece's,17,"Food, Ice Cream & Frozen Yogurt",7114 Hwy 70 S,Nashville,TN,37221,Positive,3,3
2,bCla27ma_6i_QFrGkILKrQ,sLgnx_WFCjEoPsS6NwU70Q,5,0,0,0,Our family returned for breakfast again this w...,2014-10-27 16:31:37,Le Peep,259,"Event Planning & Services, Salad, Caterers, Am...",3036 N Eagle Rd,Meridian,ID,83646,Positive,3,3
3,UsBxLh14sUpO8SdeqIiGOA,Wy8Hswf2cLQGRZN6armkag,1,1,0,0,"If I could give it a zero, I would. I order a ...",2011-08-24 23:07:08,Jack in the Box,86,"Restaurants, Fast Food, Mexican, Tacos, Burger...",6875 Hollister Ave,Goleta,CA,93117,Negative,1,1
4,mEOMAeEonZoUx2nPM3v6fg,f-WhNOSwN1aB4nRFekf01g,4,0,0,0,Id you haven't been to the Smoothie King cente...,2015-03-19 00:30:09,Smoothie King,50,"Arts & Entertainment, Ticket Sales, Food, Juic...",1501 Dave Dixon Drive Space 101-102,New Orleans,LA,70113,Positive,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586655,D-hCb9hGPFc1ApjPF6PevQ,VgPDZyDLIWe4NVetnvjqig,3,3,1,0,Eh. It was just ok. While visiting Tampa som...,2019-03-02 13:06:11,First Watch,219,"Breakfast & Brunch, Diners, American (Traditio...",3712 Henderson Blvd,Tampa,FL,33609,Positive,3,2
586657,6Hmh8UC5K0oBgp3_D5doDQ,BxveKq0rKp52EWooIDK54w,2,3,1,0,Where do i begin. Overall the food was fine. I...,2019-12-08 19:24:12,Denny's,88,"Breakfast & Brunch, American (Traditional), Re...",3155 E Fairview Ave,Meridian,ID,83642,Negative,1,1
586658,UfevNSM_H14XXWZFlHYPoA,TNtcjnta11CpDebuBNdoug,2,0,1,0,Our waiter was good but a bit rushed. I didn't...,2017-10-22 20:55:12,Red Robin Gourmet Burgers and Brews,83,"Home Services, American (New), Contractors, Am...",130 Gravois Bluffs Cir,Fenton,MO,63026,Negative,1,1
586659,LHWtjTG7e1NzNPYUbUo-9w,rgeuy1qbw6Z8B6CSVANHIA,5,1,1,1,I've been to the other Federal Donuts location...,2012-10-13 14:39:37,Federal Donuts,1464,"Donuts, Sandwiches, Soul Food, Food, Coffee & ...",1632 Sansom St,Philadelphia,PA,19103,Positive,3,3
586660,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5,1,0,1,Don't misinterpret my 5-star review....I don't...,2016-04-30 01:02:34,Wendy's,55,"Restaurants, Burgers, Food, Fast Food",2130 Hampton Avenue,St.Louis,MO,63139,Positive,3,3

In [11]:
df = train_model_df[['business_id','text', 'roberta_score']]
df = df.dropna(subset=['business_id','text', 'roberta_score'])
df

,business_id,text,roberta_score
0,0pMj5xUAecW9o1P35B0AMw,Great staff always helps and always nice. Alwa...,3
1,8QnuWGVNBhzyYXGSeRdi4g,After my ROTD yesterday of a different Sweet ...,3
2,sLgnx_WFCjEoPsS6NwU70Q,Our family returned for breakfast again this w...,3
3,Wy8Hswf2cLQGRZN6armkag,"If I could give it a zero, I would. I order a ...",1
4,f-WhNOSwN1aB4nRFekf01g,Id you haven't been to the Smoothie King cente...,3
...,...,...,...
586655,VgPDZyDLIWe4NVetnvjqig,Eh. It was just ok. While visiting Tampa som...,3
586657,BxveKq0rKp52EWooIDK54w,Where do i begin. Overall the food was fine. I...,1
586658,TNtcjnta11CpDebuBNdoug,Our waiter was good but a bit rushed. I didn't...,1
586659,rgeuy1qbw6Z8B6CSVANHIA,I've been to the other Federal Donuts location...,3
586660,1_BVWDzi5cVqWxNe9bOMMQ,Don't misinterpret my 5-star review....I don't...,3

In [12]:
#Split into Train and Test (80-20)
train_df, test_df = train_test_split(
    df, 
    test_size=0.2, 
    random_state=42, 
    stratify=df['roberta_score'])

print(f"Training data shape: {train_df.shape}")
print(f"Test data shape: {test_df.shape}")

Training data shape: (452068, 3)
Test data shape: (113018, 3)

In [13]:
#Split into Train and Validation (80-20)
X_train, X_val, y_train, y_val = train_test_split(
    train_df['text'].values, 
    train_df['roberta_score'].values, 
    test_size=0.2, 
    random_state=42, 
    stratify=train_df['roberta_score']
)

# Prepare the test set
X_test = test_df['text'].values
y_test = test_df['roberta_score'].values

print(f"Training samples: {len(X_train)}, Validation samples: {len(X_val)}, Test samples: {len(X_test)}")

Training samples: 361654, Validation samples: 90414, Test samples: 113018